export const greetings = [
	`Wassup, homie?`,
	`Yo, what's up?`,
	`Welcome, boss.`,
	`How you doin' today?`,
	`Hey, what can I do for ya?`,
	`What's good, playa?`,
	`It's your boy Kal, what you got for me?`,
	`What's crackin', big dog?`,
	`Yo, yo, yo! What can I assist you with today?`,
	`Ain't no thing, what you need?`,
	`What's shaking, my man?`,
	`What's good in the hood, boss?`,
	`How can I help you out, playa?`,
	`Whassup, bossman?`,
	`What's good, my dude?`,
	`What it do, boss?`,
	`Hey, hey, hey! What can I do for ya today, playa?`,
	`Sup, boss? How can I assist you?`,
	`Wassup, what's on your mind, homie?`,
	`Hey there, big man! You need something?`,
	`Watcha need, my dude?`,
	`What you got for me, boss?`,
	`What's up, my man? How can I help?`,
	`Hey, hey - what can I do ya for?`,
	`Ayo, boss! Wass good?`,
	`Howdy, my man. Whaddya need today?`,
	`Yo, yo, whass good? How can I assist you today, homie?`,
	`Sup, boss? What you need?`,
	`Howdy, partner. What can I help you with?`,
	`Yo, yo, wassup? Whatcha need, bossman?`,
	`Hey there, my guy. How can I help you today?`,
	`What's on your mind, boss?`,
	`How ya livin', big dog? What you need?`,
	`What's good in the hood, my man?`,
	`Wassup, player? Lemme know how I can be of service.`,
	`Hey, hey - what's on your mind, boss?`,
	`What can I do for ya, my dude?`,
	`Whass good, playa? What you need today?`,
	`What's the word, boss? How can I assist ya?`,
	`Hey there, what's on your mind, homie?`,
	`Whassup, my guy? How can I help ya out?`,
	`Sup, boss? Watcha need?`,
	`How are you doing today, big dog? What can I help you with?`,
	`Yo, yo - whass good, bossman?`,
	`What's on your mind, my man? What can I assist you with?`,
	`Hey there, partner. What can I do for ya?`,
	`What you need, playa? Holla at me.`,
	`What's up, boss? Lemme know how I can help.`,
	`Yo, yo, wassup? Whatcha need, homie?`,
	`Wass good, big man? How can I assist you today?`,
] as const
